### ISSUE TITLE
`gulp-deporder` dependancy `gulp-util` has been deprecated

### ISSUE THREAD

**Issue by orionrush** [mkleehammer/gulp-deporder#9]
`gulp-deporder` dependancy `gulp-util` has been deprecated

see [ https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5]( https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5).

**Comment by lorepirri** [comment]
The #8 was merged and removed the `gulp-util` dependency removed.

How about a release? @mkleehammer if you need any help, please let us know.

**Comment by mkleehammer** [comment]
Done: v1.2.0

Sorry for the delay.  I haven't been using node for quite a while and didn't notice.  It's been a while since I published on npm, so let me know if something doesn't look right.

**Comment by lorepirri** [comment]
Thanks a lot for the fast release! It does look like working to me :) keep up with the good job!
